name: interactive-card-details-form-main

on:
  push:
    branches:
      - main
    paths:
      - interactive-card-details-form-main/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Change Directory
        run: cd interactive-card-details-form-main/card-details

      - name: Print Current Directory
        run: pwd
      
      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
