name: interactive-card-details-form-main

on:
  push:
    branches:
      - main
    paths:
      - interactive-card-details-form-main/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       working-directory: ./interactive-card-details-form-main/card-details

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1

      - name: Install Dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Build Project
        run: npm run build
        working-directory: ${{env.working-directory}}

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/card-details
