name: interactive-card-details-form-main

on:
  push:
    branches:
      - main
    paths:
      - interactive-card-details-form-main/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Navigate to workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: Change Directory
        run: cd interactive-card-details-form-main/card-details
      
      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
